- fail:
    msg: "OS is not Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Add Dockerâ€™s official GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Get Ubuntu release
  shell: "lsb_release -cs"
  register: ubuntu_release

- name: Set up Docker stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release.stdout }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - restart docker

- name: Add user {{ user }} to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.14.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777
